// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.

package test

import (
	go_context "context"
	go_net_http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	pkg_errors "github.com/pkg/errors"
)

type ServiceGoTSRPCClient interface {
	SetBar(ctx go_context.Context, bar string) (retSetBar_0 State, clientErr error)
	SetFoo(ctx go_context.Context, foo string) (retSetFoo_0 State, clientErr error)
}

type HTTPServiceGoTSRPCClient struct {
	URL      string
	EndPoint string
	Client   gotsrpc.Client
}

func NewDefaultServiceGoTSRPCClient(url string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClient(url, "/service")
}

func NewServiceGoTSRPCClient(url string, endpoint string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClientWithClient(url, endpoint, nil)
}

func NewServiceGoTSRPCClientWithClient(url string, endpoint string, client *go_net_http.Client) *HTTPServiceGoTSRPCClient {
	return &HTTPServiceGoTSRPCClient{
		URL:      url,
		EndPoint: endpoint,
		Client:   gotsrpc.NewClientWithHttpClient(client),
	}
}
func (tsc *HTTPServiceGoTSRPCClient) SetBar(ctx go_context.Context, bar string) (retSetBar_0 State, clientErr error) {
	args := []interface{}{bar}
	reply := []interface{}{&retSetBar_0}
	clientErr = tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "SetBar", args, reply)
	if clientErr != nil {
		clientErr = pkg_errors.WithMessage(clientErr, "failed to call test.ServiceGoTSRPCProxy SetBar")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) SetFoo(ctx go_context.Context, foo string) (retSetFoo_0 State, clientErr error) {
	args := []interface{}{foo}
	reply := []interface{}{&retSetFoo_0}
	clientErr = tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "SetFoo", args, reply)
	if clientErr != nil {
		clientErr = pkg_errors.WithMessage(clientErr, "failed to call test.ServiceGoTSRPCProxy SetFoo")
	}
	return
}
